"""fix booking model

Revision ID: 42bdac4da18d
Revises: 5992e8148558
Create Date: 2026-03-24 19:10:47.960013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42bdac4da18d'
down_revision: Union[str, Sequence[str], None] = '5992e8148558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rental_plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'booked', 'allocated', 'ready_for_pickup', 'picked_up', 'returned', 'overdue', name='bookingstatus'), nullable=False),
    sa.Column('pickup_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('deposit_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rent_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rental_plan_id'], ['rental_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_id'), 'bookings', ['id'], unique=False)
    op.add_column('assets', sa.Column('asset_code', sa.String(), nullable=False))
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_column('assets', 'asset_code')
    op.drop_index(op.f('ix_bookings_id'), table_name='bookings')
    op.drop_table('bookings')
    # ### end Alembic commands ###
