"""add alocation

Revision ID: a39c4a0e973c
Revises: fb5b43e048f2
Create Date: 2026-03-28 11:48:20.090670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a39c4a0e973c'
down_revision: Union[str, Sequence[str], None] = 'fb5b43e048f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('returned_at', sa.Date(), nullable=False),
    sa.Column('days_late', sa.Integer(), nullable=False),
    sa.Column('fine_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('deposit_refunded', sa.Boolean(), nullable=False),
    sa.Column('processed_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returns_booking_id'), 'returns', ['booking_id'], unique=False)
    op.create_index(op.f('ix_returns_id'), 'returns', ['id'], unique=False)
    op.drop_constraint(op.f('payments_razorpay_order_id_key'), 'payments', type_='unique')
    op.drop_constraint(op.f('payments_razorpay_payment_id_key'), 'payments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('payments_razorpay_payment_id_key'), 'payments', ['razorpay_payment_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('payments_razorpay_order_id_key'), 'payments', ['razorpay_order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_returns_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_booking_id'), table_name='returns')
    op.drop_table('returns')
    # ### end Alembic commands ###
