"""add payments table

Revision ID: af96a38e479f
Revises: a18507cdf28c
Create Date: 2026-03-24 20:42:38.736159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af96a38e479f'
down_revision: Union[str, Sequence[str], None] = 'a18507cdf28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_unique_constraint(None, 'payments', ['razorpay_payment_id'])
    op.create_unique_constraint(None, 'payments', ['razorpay_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    # ### end Alembic commands ###
