"""add qr code path to assets

Revision ID: cde0576d3bcd
Revises: 1473dd2a501f
Create Date: 2026-06-05 12:21:21.645310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cde0576d3bcd'
down_revision: Union[str, Sequence[str], None] = '1473dd2a501f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('qr_code_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'qr_code_path')
    # ### end Alembic commands ###
