"""add alocation

Revision ID: fb5b43e048f2
Revises: af96a38e479f
Create Date: 2026-03-28 10:43:50.405103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb5b43e048f2'
down_revision: Union[str, Sequence[str], None] = 'af96a38e479f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('allocated_by', sa.Integer(), nullable=False),
    sa.Column('allocated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['allocated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allocations_booking_id'), 'allocations', ['booking_id'], unique=False)
    op.create_index(op.f('ix_allocations_id'), 'allocations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_allocations_id'), table_name='allocations')
    op.drop_index(op.f('ix_allocations_booking_id'), table_name='allocations')
    op.drop_table('allocations')
    # ### end Alembic commands ###
