"""init tables

Revision ID: fd7d1b927c3f
Revises: 332a96baaa76
Create Date: 2026-04-19 10:14:12.524310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd7d1b927c3f'
down_revision: Union[str, Sequence[str], None] = '332a96baaa76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = {column["name"] for column in inspector.get_columns("assets")}

    if "is_in_dry_cleaning" not in columns:
        op.add_column(
            "assets",
            sa.Column(
                "is_in_dry_cleaning",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )
        op.alter_column("assets", "is_in_dry_cleaning", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'is_in_dry_cleaning')
    # ### end Alembic commands ###
